version: "3.8" 

services:
  ping:
    build:
      context: .
      dockerfile: single-stage.dockerfile
    restart: always
    expose:
      - '8080'
    environment:
      - PING_LISTEN_PORT=8080
    deploy: 
      replicas: 4
    networks:
      - mynet
  nginx:
    image: nginx
    restart: always
    depends_on: 
      - ping
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - '5001:80'
    networks:
      - mynet
networks:
  mynet:
    driver: bridge